//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthcareManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secretary : User
    {
        public int ExperienceYears { get; set; }

        public Secretary(string firstname, string lastname, string cin, DateTime selectedDate, string password, bool superUser, string phoneNumber, string role, string city) :
            base(firstname, lastname, cin, selectedDate, password, superUser, phoneNumber, role, city)
        {
            
        }
    }
}
